### ISSUE TITLE
Copy-editing

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/sense-hat-pong#1]
Hi @LornaLynch, could I have a copy-edit of this please.

**Comment by LornaLynch** [comment]
Coming up :)

**Comment by LornaLynch** [comment]
I've just noticed there's no image to correspond to the "Single LED illuminated" tag in the worksheet. Could this be added? 

ETA the "Three LEDs illuminated" image is also missing :)

**Comment by LornaLynch** [comment]
Can we add a "What next?" section at the end?

**Comment by MarcScott** [comment]
Thanks - I'll knock something together until Sam can edit his Sense HAT picture
Will add a "What next?" section

**Comment by LornaLynch** [comment]
Cheers! Other than this, I think we're done. Will just have a final look through.

**Comment by MarcScott** [comment]
images added and what next?
