### ISSUE TITLE
Code Issue

### ISSUE THREAD

**Issue by savage-hacker14** [raspberrypilearning/sense-hat-pong#2]

**Comment by savage-hacker14** [comment]
I am getting an error about "SenseHat" object having no attribute "getch". Could you please fix this.
Thanks!

**Comment by MarcScott** [comment]
Sounds like a syntax error. The `getch` is a _get character_ call to the `curses` module, not the `SenseHat` module. Could you attach your code so I can have a look

**Comment by savage-hacker14** [comment]
Hi Marc,

It was an error with me typing your code. For the "key = screen.getch()" I typed "key = sense.getch()". There isn't an error in the code, just my mistake.

@savage-hacker14

On Mar 7, 2016, at 05:35, Marc Scott notifications@github.com wrote:

Sounds like a syntax error. The getch is a get character call to the curses module. Could you attach your code so I can have a look

**Comment by MarcScott** [comment]
Excellent - hope it all works out for you.
