### ISSUE TITLE
Copy edit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/sense-hat-pong#3]
Hi @LornaLynch and @lauraclay 
Could I get a copy edit on this rewrite please. Almost everything has changed, so the diffs won't be very useful.
https://github.com/raspberrypilearning/sense-hat-pong/tree/stick-update
Thank in advance

**Comment by LornaLynch** [comment]
Done :)

**Comment by MarcScott** [comment]
Awesome - thanks
